### ISSUE TITLE
FR2. Database

### ISSUE THREAD

**Issue by TheOneWhoCodes** [SIU-CS/Biggie_Software-production#3]
The database shall store information such as users and stall status

Tasks
- [x] Create database tables to manage stalls, payment status, and time purchased - Andrew & Avtar
- [x] Add each stall paid to the DB as the payment is made - Andrew
- [x] Run a simulation that changes stall information to paid and show how long it was paid for - Avtar
- [x] Point purchased stall to the specific user that purchased time there - Andrew [OMITTED]

**Comment by avatar4444** [comment]
Task 4 I though we were not tracking who paid for each spot, to avoid conflict in case that person leaves early and someone else has to park there.

**Comment by TheOneWhoCodes** [comment]
Good point. We can move past this for now and get feedback at a later date.
